# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXNOT0NFN5vx_p8cIAgrm4uwVL2oRsd-
"""

pip install diffusers

pip install transformers

pip install torch

pip install accelerate

pip install safetensors

from diffusers import StableDiffusionPipeline
import torch

# Load the pre-trained model (You need Hugging Face token for private models)
model_id = "CompVis/stable-diffusion-v1-4"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

from diffusers import StableDiffusionPipeline
import torch

model_id = "CompVis/stable-diffusion-v1-4"

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float32)
pipe = pipe.to(device)

pipe.enable_attention_slicing()

prompt = "A magical beach with beautiful sunset"
image = pipe(prompt).images[0]
image.save("output.png")
image.show()

prompt = "a futuristic cityscape at sunset, digital art"
image = pipe(prompt).images[0]

# Save the image
image.save("generated_image.png")
image.show()

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
from IPython.display import display

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")  # Use GPU
pipe.enable_attention_slicing()

prompt ="A quiet path in a moss-covered forest after rain, wet leaves, puddles reflecting trees, natural soft light, DSLR quality"
print("Generating image...")
image = pipe(prompt).images[0]
image.save("generated_image.png")

# Display in Colab
display(image)